export type RuleDescriptionKey =
  | 'matchLength'
  | 'matchCount'
  | 'minimumHan'
  | 'doraCountsTowardMinimumHan'
  | 'startingPoints'
  | 'targetPoints'
  | 'returnPoints'
  | 'bankruptcyEndsMatch'
  | 'suddenDeathTarget'
  | 'allowWestRound'
  | 'maxExtraRoundWind'
  | 'agariYame'
  | 'tenpaiYame'
  | 'useUma'
  | 'useOka'
  | 'leftoverRiichiStickMode'
  | 'allowOpenTanyao'
  | 'akaDora'
  | 'ippatsu'
  | 'allowDoubleYakuman'
  | 'multipleYakuman'
  | 'allowAncientYaku'
  | 'kiriageMangan'
  | 'doubleWindPairFu'
  | 'allowKyuushuKyuuhai'
  | 'abortOnFourWinds'
  | 'abortOnFourRiichi'
  | 'abortOnFourKans'
  | 'allowKokushiChankanAnkan'
  | 'forbidKuikae'
  | 'tripleRonMode';

export const ruleDescriptions: Record<RuleDescriptionKey, string> = {
  matchLength: '东风场默认到东四局，南风场默认到南四局',
  matchCount: '使用当前四人东风或四人南风预设连续进行的完整对局场数；每场均从起始点数重新开始并独立结算',
  minimumHan: '番数累计到达目标及以上方可和牌',
  doraCountsTowardMinimumHan: '开启后番缚判定计入普通宝牌和赤宝牌，不计入里宝牌；关闭后宝牌不计入番缚',
  startingPoints: '每名玩家开局持有的点数',
  targetPoints: '预定结束时用于判断延长局或突然死亡的目标点数',
  returnPoints: '最终排名结算时的返还基准点',
  bankruptcyEndsMatch: '开启后，任意玩家点数低于击飞线时比赛立即结束',
  suddenDeathTarget: '延长局中有人达到或超过该点数时，比赛结束',
  allowWestRound: '开启后，南风场无人达到目标点数时可以进入延长局',
  maxExtraRoundWind: '限制延长局最多进行到哪个场风',
  agariYame: '最终局庄家和牌且排名满足条件时，可以结束比赛',
  tenpaiYame: '最终局庄家流局听牌且排名满足条件时，可以结束比赛',
  useUma: '比赛结束后按名次追加点数',
  useOka: '是否允许截和',
  leftoverRiichiStickMode: '比赛结束仍留在桌面的供托立直棒如何分配',
  allowOpenTanyao: '允许副露后的断幺九成立',
  akaDora: '使用红五作为赤宝牌，计入额外宝牌番',
  ippatsu: '允许立直后一巡内无鸣牌时的一发役',
  allowDoubleYakuman: '允许部分役满按双倍役满计算',
  multipleYakuman: '允许多个役满同时累计',
  allowAncientYaku: '开启后额外启用古役判断',
  kiriageMangan: '四番三十符和三番六十符按满贯计算',
  doubleWindPairFu: '自风与场风相同的雀头按四符计算；关闭时按二符计算',
  allowKyuushuKyuuhai: '第一巡摸牌后，手牌含九种及以上幺九牌时允许宣告流局',
  abortOnFourWinds: '第一巡四名玩家依次打出同一种风牌时流局',
  abortOnFourRiichi: '四名玩家全部立直后流局',
  abortOnFourKans: '同一局出现四次杠且不属于同一玩家四杠子时流局',
  allowKokushiChankanAnkan: '允许国士无双在其他玩家暗杠时抢杠和',
  forbidKuikae: '开启后，吃碰后的第一次弃牌不得打出与本次鸣牌相同或可构成同一顺子的牌',
  tripleRonMode: '开启时三名玩家可同时荣和；关闭时沿用现有三家和流局处理',
};
