export type RuleDescriptionKey =
  | 'matchLength'
  | 'roundCount'
  | 'startingPoints'
  | 'targetPoints'
  | 'returnPoints'
  | 'bankruptcyEndsMatch'
  | 'suddenDeathTarget'
  | 'allowWestRound'
  | 'maxExtraRoundWind'
  | 'agariYame'
  | 'tenpaiYame'
  | 'useUma'
  | 'useOka'
  | 'leftoverRiichiStickMode'
  | 'allowOpenTanyao'
  | 'akaDora'
  | 'ippatsu'
  | 'allowDoubleYakuman'
  | 'multipleYakuman'
  | 'allowAncientYaku'
  | 'kiriageMangan'
  | 'doubleWindPairFu'
  | 'allowKyuushuKyuuhai'
  | 'abortOnFourWinds'
  | 'abortOnFourRiichi'
  | 'abortOnFourKans'
  | 'allowKokushiChankanAnkan'
  | 'tripleRonMode';

export const ruleDescriptions: Record<RuleDescriptionKey, string> = {
  matchLength: '东风场默认到东四局，南风场默认到南四局',
  roundCount: '设置整场一共进行几个场风轮次，每轮结束后都会进入点数结算',
  startingPoints: '每名玩家开局持有的点数',
  targetPoints: '预定结束时用于判断延长局或突然死亡的目标点数',
  returnPoints: '最终排名结算时的返还基准点',
  bankruptcyEndsMatch: '开启后，任意玩家点数低于击飞线时比赛立即结束',
  suddenDeathTarget: '延长局中有人达到或超过该点数时，比赛结束',
  allowWestRound: '开启后，南风场无人达到目标点数时可以进入延长局',
  maxExtraRoundWind: '限制延长局最多进行到哪个场风',
  agariYame: '最终局庄家和牌且排名满足条件时，可以结束比赛',
  tenpaiYame: '最终局庄家流局听牌且排名满足条件时，可以结束比赛',
  useUma: '比赛结束后按名次追加点数',
  useOka: '是否允许截和',
  leftoverRiichiStickMode: '比赛结束仍留在桌面的供托立直棒如何分配',
  allowOpenTanyao: '允许副露后的断幺九成立',
  akaDora: '使用红五作为赤宝牌，计入额外宝牌番',
  ippatsu: '允许立直后一巡内无鸣牌时的一发役',
  allowDoubleYakuman: '允许部分役满按双倍役满计算',
  multipleYakuman: '允许多个役满同时累计',
  allowAncientYaku: '开启后额外启用古役判断',
  kiriageMangan: '四番三十符和三番六十符按满贯计算',
  doubleWindPairFu: '自风与场风相同的雀头按四符计算；关闭时按二符计算',
  allowKyuushuKyuuhai: '第一巡摸牌后，手牌含九种及以上幺九牌时允许宣告流局',
  abortOnFourWinds: '第一巡四名玩家依次打出同一种风牌时流局',
  abortOnFourRiichi: '四名玩家全部立直后流局',
  abortOnFourKans: '同一局出现四次杠且不属于同一玩家四杠子时流局',
  allowKokushiChankanAnkan: '允许国士无双在其他玩家暗杠时抢杠和',
  tripleRonMode: '三名玩家同时荣和时，选择继续结算或改为流局',
};
