import { normalYaku, type YakuhaiSource, type YakuResult } from '../types';

export const NORMAL_YAKU = {
  riichi: () => normalYaku('riichi', '立直', 1, false),
  doubleRiichi: () => normalYaku('double-riichi', '双立直', 2, false),
  ippatsu: () => normalYaku('ippatsu', '一发', 1, false),
  menzenTsumo: () => normalYaku('menzen-tsumo', '门前清自摸', 1, false),
  pinfu: () => normalYaku('pinfu', '平和', 1, false),
  iipeikou: () => normalYaku('iipeikou', '一杯口', 1, false),
  tanyao: () => normalYaku('tanyao', '断幺九', 1, true),
  yakuhai: (name = '役牌', sourceTile?: YakuhaiSource) => normalYaku('yakuhai', name, 1, true, undefined, undefined, sourceTile),
  haitei: () => normalYaku('haitei', '海底摸月', 1, true),
  houtei: () => normalYaku('houtei', '河底捞鱼', 1, true),
  rinshan: () => normalYaku('rinshan-kaihou', '岭上开花', 1, true),
  chankan: () => normalYaku('chankan', '抢杠', 1, true),
  chiitoitsu: () => normalYaku('chiitoitsu', '七对子', 2, false),
  toitoi: () => normalYaku('toitoi', '对对和', 2, true),
  sanankou: () => normalYaku('sanankou', '三暗刻', 2, true),
  sanshokuDoujun: (closed: boolean) => normalYaku('sanshoku-doujun', '三色同顺', closed ? 2 : 1, true, 2, 1),
  sanshokuDoukou: () => normalYaku('sanshoku-doukou', '三色同刻', 2, true),
  sankantsu: () => normalYaku('sankantsu', '三杠子', 2, true),
  shousangen: () => normalYaku('shousangen', '小三元', 2, true),
  ittsu: (closed: boolean) => normalYaku('ittsu', '一气通贯', closed ? 2 : 1, true, 2, 1),
  chanta: (closed: boolean) => normalYaku('chanta', '混全带幺九', closed ? 2 : 1, true, 2, 1),
  honroutou: () => normalYaku('honroutou', '混老头', 2, true),
  ryanpeikou: () => normalYaku('ryanpeikou', '二杯口', 3, false),
  junchan: (closed: boolean) => normalYaku('junchan', '纯全带幺九', closed ? 3 : 2, true, 3, 2),
  honitsu: (closed: boolean) => normalYaku('honitsu', '混一色', closed ? 3 : 2, true, 3, 2),
  chinitsu: (closed: boolean) => normalYaku('chinitsu', '清一色', closed ? 6 : 5, true, 6, 5),
} satisfies Record<string, (...args: any[]) => YakuResult>;
