import { normalYaku, type YakuResult } from '../types';

export const NORMAL_YAKU = {
  riichi: () => normalYaku('立直', 1, false),
  doubleRiichi: () => normalYaku('双立直', 2, false),
  ippatsu: () => normalYaku('一发', 1, false),
  menzenTsumo: () => normalYaku('门前清自摸', 1, false),
  pinfu: () => normalYaku('平和', 1, false),
  iipeikou: () => normalYaku('一杯口', 1, false),
  tanyao: () => normalYaku('断幺九', 1, true),
  yakuhai: (name = '役牌') => normalYaku(name, 1, true),
  haitei: () => normalYaku('海底摸月', 1, true),
  houtei: () => normalYaku('河底捞鱼', 1, true),
  rinshan: () => normalYaku('岭上开花', 1, true),
  chankan: () => normalYaku('抢杠', 1, true),
  chiitoitsu: () => normalYaku('七对子', 2, false),
  toitoi: () => normalYaku('对对和', 2, true),
  sanankou: () => normalYaku('三暗刻', 2, true),
  sanshokuDoujun: (closed: boolean) => normalYaku('三色同顺', closed ? 2 : 1, true, 2, 1),
  sanshokuDoukou: () => normalYaku('三色同刻', 2, true),
  sankantsu: () => normalYaku('三杠子', 2, true),
  shousangen: () => normalYaku('小三元', 2, true),
  ittsu: (closed: boolean) => normalYaku('一气通贯', closed ? 2 : 1, true, 2, 1),
  chanta: (closed: boolean) => normalYaku('混全带幺九', closed ? 2 : 1, true, 2, 1),
  honroutou: () => normalYaku('混老头', 2, true),
  ryanpeikou: () => normalYaku('二杯口', 3, false),
  junchan: (closed: boolean) => normalYaku('纯全带幺九', closed ? 3 : 2, true, 3, 2),
  honitsu: (closed: boolean) => normalYaku('混一色', closed ? 3 : 2, true, 3, 2),
  chinitsu: (closed: boolean) => normalYaku('清一色', closed ? 6 : 5, true, 6, 5),
} satisfies Record<string, (...args: any[]) => YakuResult>;
